### ISSUE TITLE
Feature request: use the clipboard content as query and save the ChatGPT response in the clipboard

### ISSUE THREAD

**Issue by zdenys** [lyr1cx/ChatGPT-Alfred#2]
Add the possibility to take the content from the clipboard and use them as a query, obtain results from OpenAI, and save the result in the clipboard so they can be used right away without visiting OpenAI site.

Source of inspiration: https://medium.com/@miniChang8/openai-chatgpt-in-alfred-fd10bf2cefda

**Comment by lyr1cx** [comment]
Feel free to submit a MR with the feature. That would be pretty cool,..but as of now RL and work are taking over. Closing as not planned.
