### ISSUE TITLE
Bug: Symbols show up in query but not in chat itself

### ISSUE THREAD

**Issue by leabs** [lyr1cx/ChatGPT-Alfred#3]
I first noticed this when asking for some code in c++ but it generated in c. I then tried "what is 4 + 5" and see the + symbol in the browser but not in the chat itself. I will attach a screenshot

<img width="557" alt="Screenshot 2023-02-11 at 8 28 09 AM" src="https://user-images.githubusercontent.com/7071812/218260638-5fff05b1-9421-46bc-919e-a314f3a59ac9.png">

**Comment by leabs** [comment]
Seems to be an issue with encoding, replacing the + with `%2B` in the browser returns the expected result

**Comment by lyr1cx** [comment]
I suspect this could be fixed utilizing https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent but I am not the most competent javascript developer. If someone wants to contribute / has a solution feel free to submit a MR with it. I do not have the time to invest at the moment or in the near future.
