### ISSUE TITLE
May be my fault but the "submit the form" part is no longer working

### ISSUE THREAD

**Issue by jd1931smk** [lyr1cx/ChatGPT-Alfred#6]
I believe it happened once I cot a choice to select which version of chatgpt i want to use.

**Comment by lyr1cx** [comment]
I made this with my personal macbook which I no longer have, only a work related one and I don't want to debug on that for obvious reasons. If someone can replicate that and submit a MR I'll take a look and approve it.

**Comment by jd1931smk** [comment]
So I just started studying programming a few weeks ago and I don't pretend to understand exactly what's going on but with the help of Chat GPT we arrived at this edit.   it works for me.


 // ==UserScript==
// @name        ChatGPT: Parse q parameter to input
// @description Query ChatGPT from Alfred.
// @match       https://chat.openai.com/chat*
// @grant       none
// @version     1.01
// ==/UserScript==

const inputSelector = "textarea[data-id='root']"
const buttonSelector = "button[disabled]:not([class*='opacity-0'])";

// setInterval until inputSelector is on the page
const interval = setInterval(() => {
  const inputEl = document.querySelector(inputSelector);
  const sendButton = document.querySelector(buttonSelector);
  
  if (inputEl && sendButton) {
    clearInterval(interval);
    // Parse the "q" param from the query string
    const urlObj = new URL(window.location.href);
    const q = urlObj.searchParams.get("q");
    if (!q) return;

    // Set the input field to the value of the "q" param
    inputEl.value = q;

    // Find the send button and click it after a delay
    setTimeout(() => {
      sendButton.removeAttribute('disabled');
      sendButton.click();
    }, 500); // You can adjust the delay before clicking the button
  }
}, 500);
